### ISSUE TITLE
Data lost after restarting

### ISSUE THREAD

**Issue by PatWie** [scalabel/scalabel#246]
**Describe the bug**
ScaLabel is loosing the annotations.

**To Reproduce**

Create these files

```yaml
# docker-compose.yml
version: '3.8'
services:
  scalabel_init:
    build:
      context: ./
      dockerfile: data_init.Dockerfile
    volumes:
      # ScaLabel requires a strange initial directory structure.
      - scalabel-data:/data/scalabel
  # This is the ScaLabel tool itself.
  scalabel_tool:
    volumes:
      - './scalabel_configuration.yml:/opt/scalabel/configuration.yml'
      # This is where ScaLabel puts data temporary data.
      - scalabel-data:/data/scalabel
    ports:
      - '8686:8686'
      - '6379:6379'
    image: scalabel/www
    command: node app/dist/main.js --config /opt/scalabel/configuration.yml --max-old-space-size=8192
volumes:
  scalabel-data:

```

```Dockerfile
# data_init.Dockerfile
FROM alpine:3.9
RUN echo "create data" && \
  mkdir -p /data/scalabel/data && \
  echo "create items" && \
  mkdir -p /data/scalabel/items
```

```yaml
# scalabel_configuration.yml
http:
    port: 8686
storage:
    data: "/data/scalabel/data"
    itemDir: "/data/scalabel/items"
    type: "local"

```

First build it
```
docker-compose build
```

Then run it

```
docker-compose up
```

Create a project. If the task-size is such that there are two task

the output is

![Screenshot from 2020-11-02 12-59-32](https://user-images.githubusercontent.com/6756603/97865937-4b4b3d80-1d0b-11eb-89d4-99d855113921.png)

and 
```
scalabel_tool_1      | 01de7cc18b22:1:2020-11-02_11-58-43 info: Failed to get the key projects/test/saved/000000. Searching storage.
scalabel_tool_1      | 01de7cc18b22:1:2020-11-02_11-58-43 info: Failed to get the key projects/test/saved/000001. Searching storage.

```

 and annotate an image. In the vendor list there will be the annotation (see `Submitted`) in the table. 

![Screenshot from 2020-11-02 13-00-23](https://user-images.githubusercontent.com/6756603/97866008-67e77580-1d0b-11eb-9b28-e37a44846354.png)

Press Ctrl+C to gracefully shutdown the app. Restart the app via

```
docker-compose up
```

The vendor page looks like

![Screenshot from 2020-11-02 13-01-29](https://user-images.githubusercontent.com/6756603/97866139-9ebd8b80-1d0b-11eb-85aa-57c713b83aa5.png)

(Note, we lost the annotation)

and the console shows

```
scalabel_tool_1      | 16:M 02 Nov 2020 12:01:24.046 # Server initialized
scalabel_tool_1      | 16:M 02 Nov 2020 12:01:24.046 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
scalabel_tool_1      | 16:M 02 Nov 2020 12:01:24.046 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
scalabel_tool_1      | 16:M 02 Nov 2020 12:01:24.046 * Ready to accept connections
scalabel_tool_1      | 01de7cc18b22:1:2020-11-02_12-01-26 info: Requesting /dashboard?project_name=test
scalabel_tool_1      | 01de7cc18b22:1:2020-11-02_12-01-26 info: Requesting /js/dashboard.js
scalabel_tool_1      | 01de7cc18b22:1:2020-11-02_12-01-27 info: Requesting /getDashboardContents?name=test
scalabel_tool_1      | 01de7cc18b22:1:2020-11-02_12-01-27 info: Failed to get the key projects/test/saved/000000. Searching storage.
scalabel_tool_1      | 01de7cc18b22:1:2020-11-02_12-01-27 info: Failed to get the key projects/test/saved/000001. Searching storage.
scalabel_tool_1      | 01de7cc18b22:1:2020-11-02_12-01-28 info: Requesting /dashboard?project_name=test
scalabel_tool_1      | 01de7cc18b22:1:2020-11-02_12-01-28 info: Requesting /js/dashboard.js
scalabel_tool_1      | 01de7cc18b22:1:2020-11-02_12-01-28 info: Requesting /getDashboardContents?name=test
scalabel_tool_1      | 01de7cc18b22:1:2020-11-02_12-01-28 info: Failed to get the key projects/test/saved/000000. Searching storage.
scalabel_tool_1      | 01de7cc18b22:1:2020-11-02_12-01-28 info: Failed to get the key projects/test/saved/000001. Searching storage.
scalabel_tool_1      | 01de7cc18b22:1:2020-11-02_12-01-28 info: Requesting /favicon.ico

```

**Expected behavior**
The annotation should be persistent over restarting the app. The folder

```
user@host $ docker-compose exec scalabel_tool bash
user@container $  dir /data/scalabel/data/projects/test/saved/
dir: cannot access '/data/scalabel/data/projects/test/saved/': No such file or directory
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome

**Additional context**
